version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # Run at 4:00 AM on Monday, 5 hours before deployment
      time: "04:00"
      day: "monday"
    # Raise pull requests for version updates against the `main` branch
    target-branch: "main"
    # Labels on pull requests
    labels:
      - "dependencies"
      - "automerge"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Specify security updates separately
    security-updates-only: false