name: Verify PR

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Authenticate with Google Drive
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" > credentials.json

      - name: Install googleapis library
        run: npm install googleapis

      - name: Check Dependabot alerts
        run: npm audit

      - name: Run pre-build script
        run: node scripts/process-gpx.js

      - name: Build website
        run: npm run build
